clearlydefined/service

- README.md
- business/aggregator.js
- business/summarizer.js
- lib/config.js
- lib/github.js
- lib/utils.js
- providers/curation/github.js
- providers/harvest/azblob.js
- providers/harvest/vsts.js
- providers/summary/clearlydescribed.js
- routes/curations.js
- routes/harvest.js
- routes/packages.js
Some pretty sweeping changes to 
* update url structure (see readme)
* Integrate harvesting storage with the Azure blob storage configuration used in the crawler
* support getting the effective output based on a proposed PR
* enhance summarization to include NPM info found on packages
* add some handy comments here and there.
> Updates and integrate with crawler

- .travis.yml
Not much to see here. Travis will execute `npm test` which currently runs `eslint` and our (non-existent) tests 😜 .
Need someone with permissions to enable travis for `clearlydefined/service`: https://travis-ci.org/profile/clearlydefined
> Add initial PR builder travis job

- lib/config.js
- package-lock.json
- package.json
- providers/curation/github.js
- providers/harvest/azblob.js
- routes/curations.js
- routes/harvest.js
- routes/packages.js
to make data more discoverable, we need to be able to search for curations and harvested data. This PR adds curation prefix accessing in a really simplistic way.
* The service keeps a clone (on demand) of the entire curation repo. This obviously does not scale but will do for a while. There is a configurable TTL for the clone after which a `git pull` is done before accessing.
* The file system is then used as the search space and all `.yaml` files under the given prefix are found, and their revisions teased out.
Eventually we will need something more than this. Perhaps a level based query, perhaps a real database, ... who knows. Oh, and this does not do pagination.
Having said all that, it works and we have precisely one curation in the dev repo right now :-)
For the harvest endpoint we …
> add curation, harvest and packages search endpoints

- lib/curation.js
- package-lock.json
- package.json
- providers/curation/github.js
- routes/webhook.js
- schemas/curation.json
- test/fixtures/curation-invalid.yaml
- test/fixtures/curation-valid.yaml
- test/lib/curation.js
- test/providers/github.js
Made some decent progress: 
* Turns out `js-yaml` doesn't validate yaml files against a JSON schema spec file out of the box, so I had to research a bit on best way to do this. Came across `ajv` which works well in conjunction with `js-yaml`.
* Setup a couple tests and fixture files (one for a valid curation, another for an invalid curation) so I had a nice feedback loop as I updated the curation schema. LMK if you guys prefer a different directory structure for the `test` dir.
* Started building up the curation schema using @jeffmcaffer's initial schema as a guide
* Played a bit with `revisions` and `patternProperties` (thanks @iamwillbar) and that seems to work well. Next we need to define a `revision` object in greater detail (i.e. add `described`, `licensed`, etc).
Although this is a …
> First stab at validating curation against schema

- app.js
- package-lock.json
- routes/originGitHub.js
- routes/originNpm.js
Originally the web UI was fetching the candidate github repos and NPM modules directly from the respective origins. This had a number of issues
* some of the apis do not work for CORS calls
* It was a little challenging to manage ratelimits and caching
* There was no opportunity for unify or augmenting results
This PR implements origin searching for GitHub and NPM as pretty much straight pass throughs. There is still work to do
* augment with info like what we already have
* structure the data in a more uniform way to simplify the consumer experience
* caching
* update to use the new GitHub API token coming via auth
As it is, this is fine to release and follow up with the outlined changes.
> add "origin" search endpoints

- README.md
- app.js
- lib/config.js
- middleware/caching.js
- middleware/github.js
- package-lock.json
- package.json
- providers/caching/memory.js
- providers/caching/redis.js
- providers/curation/github.js
- routes/auth.js
- routes/curations.js
Ready for review. See clearlydefined/website#37 for the frontend portion.
This change:
* Adds GitHub authentication endpoints so that users can sign in with their GitHub account
* Adds GitHub middleware that injects a user-aware GitHub API client into the request context
* Injects the current user's GitHub teams into the request context
* Adds caching provider/middleware
Small items left to finish before merging:
In future PRs:
* Check teams & enforce permissions
* Offload more GitHub operations to the currently signed-in user; right now it's just PRs
> GitHub OAuth support

- README.md
- lib/config.js
- lib/entityCoordinates.js
- lib/resultCoordinates.js
- lib/utils.js
- package-lock.json
- package.json
- providers/curation/github.js
- providers/harvest/vsts.js
- providers/stores/abstractStore.js
- providers/stores/azblob.js
- providers/stores/file.js
- routes/curations.js
- routes/harvest.js
- routes/packages.js
- routes/swagger.yaml
- schemas/harvest.json
To support scenarios involving batches of results, add a harvest endpoint to get the statuses of a set of components.
along the way, clean up a mess of coordinate/path design and add some schema/swagger.
> Add support for listing sets available harvest results

- lib/config.js
- middleware/github.js
- middleware/permissions.js
- package-lock.json
- routes/auth.js
- routes/curations.js
- routes/harvest.js
Note the two team names in config. These can be changed; they just have to match teams in the clearlydefined org.
> Add team/permission checks for harvesting and curation

- README.md
- lib/config.js
- middleware/permissions.js
- routes/curations.js
- routes/harvest.js
- test/providers/store/fileScan.js
* make the perms teams configurable externally (env vars) to allow different environments (dev, prod, ...) to use different teams
* remove a couple of the permissions checks to make the system a little more open. Others will be added in as we add more function
> make team perms configurable and remove some checks

- middleware/github.js
This proposal separates anonymous, logged in and team users.
* anonymous -- they get a client on the req but no token. their requests will be ratelimited by GH. If we want, we can add our own token there...
* logged in -- users that have a valid GH token but are not members of any team. Their req will have a token but there will be certain operations they cannot do.
* team members -- valid GH token and they are member of a CD team. They can do various special operations.
> support anonymous users with no token

- providers/summary/scancode.js
- schemas/curation.json
- test/fixtures/curation-invalid.1.yaml
- test/fixtures/curation-invalid.2.yaml
- test/fixtures/curation-invalid.3.yaml
- test/fixtures/curation-valid.yaml
- test/lib/curation.js
- test/summary/scancode.js
The summary (and curation) schema had too much copyright info
* remove statements and authors
* add `missing` counts for holders and licenses
* add total license related file count
* add a mess of tests
> rationalize copyright info

- app.js
- business/definitionService.js
- lib/curation.js
- package-lock.json
- package.json
- providers/curation/github.js
- providers/stores/azblob.js
- providers/stores/file.js
- routes/definitions.js
- routes/webhook.js
- schemas/curation.json
- test/business/definitionServiceTest.js
- test/lib/curation.js
- test/providers/github.js
- test/routes/webhookTests.js
- test/test.js
When a curation changes we need to invalidate any cached definitions. This change rearchitects some of the webhook and the definition computation code to make it easier.
* webhook is broken into more modular pieces and much of the logic moved to the github curation service
* The definition infrastructure gets _invalidate_ style methods
* Stores get the ability to delete
* several tests added
* add the ability to get definitions and force recomputation for use on localhost where there are no webhooks
* couple of fixes along the way
> reorg to enable invalidate on webhook merge

- app.js
- business/definitionService.js
- lib/config.js
- lib/entityCoordinates.js
- routes/webhook.js
- test/providers/github.js
- test/routes/webhookCrawlerTests.js
- test/routes/webhookGitHubTests.js
When a crawler output changes the crawler will fire a webhook. Hook into that and invalidate the definition for the corresponding entity. This should be best effort and not cause any processing to fail.
> invalidate definitions on crawler webhook calls

- app.js
- lib/config.js
- package-lock.json
- package.json
Disabled by default, to enable set:
* `RATE_LIMIT_WINDOW` to the number of seconds you want to monitor a given IP for
* `RATE_LIMIT_MAX` to the maximum number of requests from an IP during the window
Note the `'trust-proxy'` setting -- I added this with the assumption that CloudFlare is fronting the request. If this isn't set, rate limits will be too aggressive as it'll think that CloudFlare's internal IP is the requester IP. This is derived from `X-Forwarded-For`; see https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-
> Rate-limit authenticated routes

- app.js
- package-lock.json
- package.json
- routes/auth.js
This is accomplished by checking if the referrer is localhost, and then
setting a cookie with the real localhost origin. This cookie is read on
finalize and substituted for the real UI in postMessage.
> Allow localhost to access dev-api

- app.js
- lib/curation.js
- package-lock.json
- package.json
- providers/summary/scancode.js
- schemas/curation.json
- schemas/definition.json
- schemas/harvest.json
- test/summary/scancode.js
update the definition schema and enhance scancode summarization as follows
* ensure props are set only if they have values
* associate all facets with each applicable file
* support license files only in the root
* update and enhance the tests
> round out scancode definition sumarization

- providers/summary/scancode.js
- test/summary/scancode.js
Rather than using the copyright holders as the attributions value, this
change uses the copyright statements in order to better support
scenarios like NOTICE file generation.
#161
> Use copyright statements when getting attributions

- package-lock.json
- package.json
- providers/summary/scancode.js
- test/summary/scancode.js
This change handles html entities and literal instances of `\n` that
appear in the copyright attribution by replacing them with more
appropriate strings.
Issue: #162 
Dependency: #166
> Handle special characters in copyright attribution

- providers/summary/clearlydefined.js
Addressing issue #178. Based on https://docs.npmjs.com/files/package.json#license there can be a license object where the spdx license is stored in the type field.
> npm license type fix

- business/aggregator.js
- business/definitionService.js
- business/summarizer.js
- lib/utils.js
- providers/summary/scancode.js
- test/business/definitionServiceTest.js
- test/summary/scancode.js
The previous notion of facets and grouping data into facets was largely coded into the scancode summarizer. With a recent redesign that introduced per-file data  such as license and copyright, the summarizers can be simplified and the facet grouping moved up a level or two and thus shared. 
This refactoring moves all the file grouping code up to the definition service and rationalizes the related tests.
Note that this does not change the definition schema so should be mergable without any data migrations.
> refactor facet computation

- providers/summary/clearlydefined.js
The issue tracker was coming back as an object because the package.json `bug` property is an object with either `url` or `email` and we normalize to a string.
> fix npm issue tracker population

- business/aggregator.js
- business/definitionService.js
- business/summarizer.js
- test/business/definitionServiceTest.js
When the service is asked for a definition about which it has no information, we'd compute the (basically empty) definititon and then store it. That just clutters up the store and opens the service to attack with people querying random stuff.
This PR changes to only store when the definition has `tools`. The summarizer tracks what tools (including `curation`) go into making up the definition. If there are none then that means we did not have any harvested data and no curations were found. That is, ClearlyDefined does not have anything in particular to say about the requested component. So, nothing to store.
> Don't store empty definitions

- app.js
- business/aggregator.js
- lib/config.js
- lib/utils.js
- package-lock.json
- package.json
- providers/curation/github.js
- providers/stores/abstractStore.js
- providers/summary/clearlydefined.js
- routes/attachments.js
- routes/content.js
- routes/definitions.js
- routes/swagger.yaml
- schemas/definition.json
- test/lib/util.js
- test/providers/github.js
- test/providers/store/fileScan.js
The crawler now captures interesting files (e.g., LICENSE.md, ...) and stores it with an opaque token (sha256 hash of the raw content). This PR adds the following to support this new data.
* API for getting the content given a token
* extraction of the relevant harvested data during summarization 
* proper merging of the file tokens during aggregation and curation
* More tests
Note that the store access technique is replicated from how we are handling the definition and harvest stores. That is, we directly access the underlying storage shared with the crawler. This may prove to be an issue in the future as we are sharing implementation details. As it is, the storage structure is pretty stable. 
Note as well that this includes a subtle change in a little used part of the schema. The …
> Handle and expose interesting file content

- business/definitionService.js
- lib/curation.js
- package-lock.json
- providers/curation/github.js
- schemas/definition.json
- test/business/definitionServiceTest.js
The current scoring tells users the score of the entire definition and includes any curations. However, 
* Tome users will only be interested in (or emphasize) particular dimensions of the definition (e.g., licensed). For example, they may not care that the source location is not known.
* Project teams should be interested in how inherently ClearlyDefined their project is. The community should be able to tell the difference between a project has no data whatsoever but has been lovingly curated by an attentive user community, and one which is loved and clarified by the project team.
To address these scenarios, this PR splits the score computation into two (using just the harvested data and using the final, curated definition) and then does this for each dimension (described and licensed) …
> compute implicit and curated scores

- business/definitionService.js
- providers/summary/scancode.js
- test/business/definitionServiceTest.js
- test/summary/scancode.js
This fixes #203. There was a missing `setIfValue` in the code that computed the definition. We cleaned up all the attributions and used those values to compute the cumulative attributions for each facet but neglected to store the cleaned up attributions on the corresponding file. 
I also took the opportunity to add some simple deduping (though not full cleanup) to the scancode summarizer and add a few tests for these cases.
> add missing copyright deduplication

- providers/summary/fossology.js
- test/summary/fossology.js
The fossology summarization was returning an incorrectly structured object `{ nomos: ...}` rather than `{ files: ... }`
There also appeared to be some issues with the regular expressions perhaps due to differences in node versions? On my windows machine with Node 8.9.4 the runtime was complaining that the expressions were invalid.
> update fossology summarization

- app.js
- business/aggregator.js
- business/definitionService.js
- lib/utils.js
- providers/summary/fossology.js
- test/business/definitionServiceTest.js
- test/lib/util.js
- test/summary/fossology.js
There was a bug in `mergeDefinition` such that new files in the supplied newDefinition were not added to the base. Fixed and added a mess of tests
Also adapted to nomos' changed to NOT base64 encode
> fix merge bug and adapt to nomos output change

- providers/curation/github.js
- routes/webhook.js
- test/providers/github.js
- test/routes/webhookGitHubTests.js
Fix the URL used in PR check to guide people to clearlydefined.io/curations/##
Note: still have to fix that route in the site. that will come in a future PR
> fix pr check url

- providers/summary/scancode.js
- test/summary/scancode.js
ScanCode file results include directories. These have no bearing in definitions so should be skipped.
> skip directory entries in scancode

- business/definitionService.js
- lib/config.js
- providers/stores/file.js
- providers/summary/clearlydefined.js
- schemas/curation.json
- schemas/definition.json
- test/business/definitionServiceTest.js
- test/fixtures/curation-valid.1.yaml
Significant refactoring of how source locations are managed.
* source location now has a `namespace` and `name` just like other coordinates. The URL is computed. 
* Curation source locations still have a `url` but that will be migrated away
* add schema version for definitions and auto recompute if the cached def's schema is old
* make the service config settings independent of the crawlers. There was as a conflict on the store provider settings (crawler wanted `cd(file)` and service wanted `file`). Makes it cleaner anyway
> refactor source location management

- providers/curation/github.js
The current code has the server caching a full copy of the curation repo locally and uses that when computing definitions. This works fine in most scenarios but when the user merges a curation, the service gets a webhook that immediately turns around and tries to (re)compute the definition. Unfortunately, the local copy of the repo will generally not have the "just merged" content. (The repo refresh period is 10 min but even if it was super fast, it will not be that fast)
This PR changes to hit GitHub all the time. That is not as bad as it seems. 
1) most components don't have curations
2) we can hit the GitHub raw content store to test for content without using tokens
3) we only recompute defintions when something might have changed (new blob, new curation) 
We can get better at this but …
> fetch fresh curations from GitHub for every def compute

- providers/stores/abstractAzblobStore.js
- providers/stores/mongo.js
- test/providers/store/azblobDefinition.js
- test/providers/store/mongoDefinition.js
obsoletes #247 
* Azure blob definitions have moved to be in their own collection but we were still appending on a /tool/definition/1 to the coordinates. Not needed. Remove and fix up tests
* The Mongo definition store tests were left in a broken state. Fix them up.
> fix mongo tests and azure definition coordinates

- business/aggregator.js
- lib/utils.js
- providers/summary/clearlydefined.js
- providers/summary/scancode.js
- test/lib/util.js
- test/providers/summary/clearlydefined.js
- test/summary/scancode.js
If we find a license on a harvested interesting file, set this to the `licensed.declared` property of the definition.
This runs early, so it can be overwritten by the package manager metadata.
@jeffmcaffer does this meet the bar for declaring a license?
The scenario I am thinking about is someone ships a `LICENSE` file with their package and doesn't register this license metadata anywhere else.
> set licensed.declared based on interesting files license

- lib/utils.js
- providers/summary/fossology.js
- test/summary/fossology.js
hitting the defintion route for `"git/github/reactiveui/reactiveui/8ed94f5d40248f409177e2cdd82e2029e9f7c601"`
before:
after:
> normalize fossology license summary to spdx only

- app.js
- package-lock.json
- package.json
- schemas/swagger.yaml
fixes #238 
turns out there were multiple issues. 
* old version of swagger-ui 
* swagger.yaml that was invalid (halfway between 2.0 and 3.0 format)
* not supplying a swagger url so swagger could not figure out base urls for referenced docs
* no route serving up the referenced files
This PR addresses all of these and gets the structure in the right format. There are still issues with the actual swagger being out of date and likely some incompatibilities with JSON schema and swagger (e.g., pattern properties). Those can be worked out in a subsequent PR.
> update swagger spec and UI

- package-lock.json
- package.json
- providers/curation/github.js
- providers/curation/memoryStore.js
- providers/curation/mongoCurationStore.js
- routes/curations.js
- routes/webhook.js
- test/providers/curation/github.js
- test/providers/curation/githubPRs.js
- test/routes/webhookGitHubTests.js
new route `/curations/sync` to synchronize all the curation PRs and recompute definitions for merged ones.
This route is locked down to the curation github team `curation-dev|curation-prod` 
Authenticate with bearer auth github token
> add curations/sync route

- providers/summary/clearlydefined.js
- test/summary/clearlyDefined.js
see spec https://guides.rubygems.org/specification-reference/#license=
There is `license (string)` and `licenses (array)`
Example of a dual licensed: https://rubygems.org/api/v1/gems/mocha.json
Interpreting to join with `OR`
> update rubygem summarizer to read licenses from registryData

- lib/utils.js
- test/summary/clearlyDefined.js
This way it will work for tags too
The revisions for git components can be commit or tag
Tag:
- https://api.clearlydefined.io/definitions/git/github/expressjs/body-parser/1.5.2
- https://github.com/expressjs/body-parser/commit/1.5.2
- https://github.com/expressjs/body-parser/tree/1.5.2
Commit:
- https://api.clearlydefined.io/definitions/git/github/expressjs/body-parser/bd386d3a7d540bac90bbdaff88f653414f6647fc
- https://github.com/expressjs/body-parser/commit/bd386d3a7d540bac90bbdaff88f653414f6647fc
- https://github.com/expressjs/body-parser/tree/bd386d3a7d540bac90bbdaff88f653414f6647fc
> change commit -> tree for github sourceUrls

- app.js
- business/noticeService.js
- package-lock.json
- package.json
- providers/stores/azblobAttachmentStore.js
- routes/notices.js
- schemas/notice-request.json
- schemas/validator.js
- test/business/noticeServiceTest.js
See [chive](https://github.com/amzn/tiny-attribution-generator)
Example: 
POST to https://api.clearlydefined.io/notices
body:
```json
{
"coordinates": [
"npm/npmjs/-/lodash/4.17.11",
"npm/npmjs/-/junk/5.88.0",
"npm/npmjs/@ant-design/icons/1.1.15",
"nuget/nuget/-/newtonsoft.json/12.0.1"
],
"output": "text|html|template|json",
"options": {"template": "<optional handlebars template>"}	
}
```
see https://github.com/amzn/tiny-attribution-generator/blob/master/default-htmltemplate.hbs for a template example
We will use the default textRenderer in chive if one is not provided
> Integrate chive to generate notice files

- business/definitionService.js
- providers/curation/github.js
- test/business/definitionServiceTest.js
- test/business/noticeServiceTest.js
three new log statements:
- 'current definition exists',
- 'definition is available'
- 'definition not available'
we want to be able to query the percentage of requests that we have
information available for. This is the sum of
'current definition exists' and 'definition is available' divided by
the sum of all three
> add telemetry to defintionService

- providers/summary/clearlydefined.js
the project layer was removed in 1.2.0 when we started inheriting poms
> update maven summarization for new harvest schema

- business/aggregator.js
- business/definitionService.js
- lib/utils.js
- providers/stores/mongo.js
- test/providers/store/mongoDefinition.js
For documents that have more than 1000 files, we will split them across different documents in the store.
This should be transparent to any callers of the store. we will get and set as one logical document.
Things to note:
- adding a partitionKey set to the canonical coordinates so we can keep multiple pages of a single document on a single partition
- storing currentPage and totalPages as metadata on the document in a `_mongo` property specific to this store and not surfaced as part of the definition
- working with some larger documents surfaced some bugs in our harvested data around the file lists, we are now treating the clearlydefined tool as the source of truth for absolute file list
> paginate the defintions in the mongo store (fixes #254)

- app.js
- bin/config.js
- business/statusService.js
- routes/status.js
list the available statuses queries: `/status/`
request counts per day: `/status/requestcount`
definition availability distribution: `/status/definitionAvailability`
components processed per day per host: `/status/processedperday`
recently crawled coordinates: `/status/recentlycrawled`
> add statusService with service and crawler queries

- app.js
we've been dropping a lot of webhooks because of `PayloadTooLargeError` 
Want to see if we can bring the number of dropped hooks down without causing too much trouble
> bump up the size limit on webhook body

- package-lock.json
All versions of handlebars are vulnerable to Prototype Pollusion.
Templates may alter an Objects' prototype, thus allowing an attacker
to execute arbitrary code on the server.
see https://www.npmjs.com/advisories/755
> bump handlebars to 4.1.0

- providers/curation/github.js
> change curation pr title to the subject line that the user entered

- lib/spdx.js
- package-lock.json
- test/lib/spdx.js
- test/providers/summary/scancode.js
we should not be accepting of all exceptions
if a non-spdx exception is used then the license is NOASSERTION
> update commons-clause exception handling

- providers/curation/github.js
see https://github.com/clearlydefined/curated-data/issues/1101
there is a problem with an issue showing up in prs
this is breaking the "all" query
we will get all of them if we query for open and closed
> workaround github issues

- providers/stores/mongo.js
- test/providers/store/mongoDefinition.js
the regex searches are not indexed
the results are way too slow and expensive to expose
> remove regex from mongo query for namespace/name

- providers/curation/mongoCurationStore.js
- routes/curations.js
- test/providers/curation/github.js
- test/providers/curation/mongoCurationStore.js
This comes up if you request 
https://api.clearlydefined.io/curations/ with no data.
We are incorrectly checking the result and get a null ref
updated test that was not properly awaiting the assertion
> fix no coordinates path for curations

- business/suggestionService.js
- test/business/suggestionServiceTest.js
this was leftover from when we switched to exact match in #431
> remove regex markers from suggestions queries

- business/definitionService.js
- providers/stores/mongo.js
- schemas/definition-1.0.json
- schemas/definitions-find.json
- test/business/definitionServiceTest.js
- test/providers/store/mongoDefinition.js
Fixes #436 
Here we add a new top level definition element for `scores`. It captures the average score across all of the dimensions (currently only licensed and described) for both curated and tools scores. The curated score is generally the score that the UI renders for the user.
> add top level scores definition element

- providers/summary/fossology.js
- test/summary/fossology.js
See-file is set when fossology detects a license related comment that references other files
Instead of marking the license for this file as NOASSERTION - we abstain from passing judgement
from the Fossology side
> [Fossology] make 'See-file' licenseId a noop

- business/definitionService.js
- routes/definitions.js
- test/business/definitionServiceTest.js
if you POST or GET for definitions you can pass `?expand=-files` to chop off the files array from the response
Thinking expand can be extended to do more interesting things later if needed
> Omit files

- bin/config.js
- business/definitionService.js
- business/statsService.js
- providers/index.js
- providers/stores/abstractAzblobStore.js
- providers/stores/abstractFileStore.js
- providers/stores/azblobDefinitionStore.js
- providers/stores/dispatchConfig.js
- providers/stores/dispatchDefinitionStore.js
- providers/stores/mongo.js
- removed average that was DOSing the DB
- add dispatch to read/write to mongo + blob storage
Plan is to use mongo as the primary and store to both blob and mongo moving forward.
Once we catch up and sync the stores, blob can become primary for listing and point lookups while mongo can be primary for queries.
Blob data will be helpful for mirroring story as well as potential search indexing.
> add definition store dispatcher

- providers/summary/clearlydefined.js
- test/summary/clearlyDefined.js
couple of different formats found for maven manifest/summary/licenses
```js
{
licenses: [{ license: { name: 'MIT' } }]
}
```
```js
{
licenses: [{ license: { url: 'https://opensource.org/licenses/MIT' } }]
}
```
```js
{
licenses: [{ url: 'https://opensource.org/licenses/MIT' }]
}
```
> incorporate maven direct urls

- business/definitionService.js
- business/statsService.js
- providers/search/azureConfig.js
- providers/search/azureSearch.js
- test/business/definitionServiceTest.js
- test/business/statsServiceTest.js
The search indexer is running now connected to the blob definition store and mapping more of the metadata.
The existing suggester for coordinates is migrated to the new search indexer, so we can remove the old one and keep a single index.
- only store to the search index manually when using in-mem definition preload
- re-enable stats queries for count+median breakdowns by type
> set up blob indexer for search

- business/definitionService.js
stringify and lowercase before comparing so it supports bot entityCoordinates and raw strings, no matter the casing
> lower the coordinates on both sides when comparing

- providers/summary/fossology.js
saw this one come up with https://clearlydefined.io/definitions/npm/npmjs/-/augur-ui-react-components/3.6.24
> add See-URL to fossology no-op list

- app.js
- business/definitionService.js
- providers/harvest/crawler.js
- test/business/definitionServiceTest.js
if a definition is not available, quick off a harvest request to go get it
fixes #497
> enable lazy harvesting of defintions

- app.js
- bin/config.js
- providers/curation/azureQueueConfig.js
- providers/curation/process.js
- providers/harvest/azureQueueConfig.js
- providers/harvest/crawlerQueue.js
- providers/harvest/crawlerQueueConfig.js
- providers/harvest/process.js
- providers/index.js
- providers/queueing/azureStorageQueue.js
- providers/queueing/memoryQueue.js
- test/providers/curation/processTest.js
- test/providers/harvest/processTest.js
- test/providers/queueing/memoryQueueTest.js
create a listener on a queue for github webhooks to process new curation events
This adds 
- `/providers/curation/process.js` to process new curations (curations)
- `/providers/harvest/process.js` to process new hooks from the crawlers (harvests)
- `/providers/harvest/crawlerQueueConfig.js` to queue messages directly to the crawler
Instead of having all the crawlers call back to the service over a webhook for harvest complete notifications, moving towards the crawlers queueing messages instead.
Instead of github calling over a webhook directly to the service for curation notifications, moving towards github hooks queueing messages directly instead
Instead of calling the crawlers from the service over HTTP to pass on new harvest requests, queue the request directly into storage so any of …
> add queue processing to the service

- routes/auth.js
Needed by https://github.com/clearlydefined/website/issues/778
Since the user needs to be informed if his contribution and all the commits would be attributed to him, we need to get from his profile his public emails, if at least one is available.
This change requires a new scope to the GitHub request so we might upgrade the service token.
> Add ability to get user public emails from Github

- lib/utils.js
- test/providers/curation/github.js
- test/providers/curation/githubPRs.js
Updates extractDate momentjs date parsing to use the recommended
'String+Format' method to explicity test for ISO 8601, "MM-DD-YYYY", or
"YYYY-MM-DD" date formats. FFI https://momentjs.com/docs/#/parsing/string/
Intercepts and verifies the logging output from an invalid contribution
as to quiet the 'validates invalid PR change' test.
Updates nodejs constructors for Buffer to safer alternatives in githubPRs.js per
https://nodejs.org/api/buffer.html#buffer_buffer_from_buffer_alloc_and_buffer_allocunsafe
Resolves #676
Signed-off-by: Tom Marble <tmarble@info9.net>
> Quiets noisy npm tests

- providers/summary/clearlydefined.js
- test/summary/clearlyDefined.js
- test/summary/clearlydefinedTests.js
Note: disjuctinve (`OR`) of license array previously handled.
> Adds support and test coverage for license{,s} as {string,array}

- README.md
In multiple places the README references a Configuration section that
does not exist. The README should not reference a section that does
not exist. This section did exist but was removed in commit c1d49f6
"update readme and swagger". The Configuration section has been
restored from that commit.
Fixes #680
> Restoring Configuration section to README.

- schemas/notice-request.json
When a POST request is made to /notices with a 'coordinates' array
exceeding a length of 5000 we return status 400 and indicate that the
array's maximum length is 5000.
Fixes #359
I was unable to find tests for the HTTP interface itself only tests that call the NoticeService which would bypass this change. I tested by hand. If there are tests for the HTTP interface as well I can add a new one there.
> Failing requests to /notices when coordinates exceed 5K.

- routes/originGitHub.js
The user/organization recommendations sorting for GitHub Harvest have
been changed from "repositories" to best match (the GitHub
default). This fixes an issue where an exact match is not the first
item in the results and a case where an exact match doesn't show up at
all in the recommendations (the user/org has few repos but their ID is
a substring of many other IDs; since we limit to first 100 results).
Fixes #661
> Changing github harvest recommendations to sort by best match.

- providers/summary/clearlydefined.js
- test/summary/clearlyDefined.js
- test/summary/clearlydefinedTests.js
Handles legacy licenses key as either:
- a string
- an array of strings
- an array of objects (where each type key has the license string)
Resolves: #458 (bis)
Signed-off-by: Tom Marble <tmarble@info9.net>
> Fixes NPM summarizer for legacy licenses key

- schemas/swagger.yaml
This PR adds all of the types and providers actually supported by clearlydefined to the swagger API docs.
> Flesh out types and providers

- lib/utils.js
Before (broken): http://central.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-scala_2/11/2.11.1/jackson-module-scala_2.11-2.11.1-sources.jar
After (not broken): https://search.maven.org/remotecontent?filepath=com/fasterxml/jackson/module/jackson-module-scala_2.11/2.11.1/jackson-module-scala_2.11-2.11.1-sources.jar
RE: [issue 707](https://github.com/clearlydefined/service/issues/707)
> Updated mavencentral source url

- lib/utils.js
Based on this [issue](https://github.com/clearlydefined/service/issues/757). Add https://aka.ms/azureml-sdk-license to Microsoft EULA.
> Add url Microsoft EULA

- business/noticeService.js
- test/business/noticeServiceTest.js
Some packages have too many files that would be included in the notice.
Example: https://clearlydefined.io/definitions/git/github/tensorflow/tensorflow/3ffdb91f122f556a74a6e1efd2469bfe1063cb5c.
This adds a simple filter to exclude anything that's not at the root of the repository (any files with `/` in the path).
> Exclude non-root package file contents from NOTICE generation

- lib/utils.js
- test/lib/util.js
- test/providers/summary/fossology.js
We only consider files named `license` (+ variants) as being valid licenses right now. This change will add `copying` (+ a few extension variants) to the list of valid license file names. The list of variants is not the same between the two base names on purpose.
Updated tests for `isLicenseFile` to check that we have same behavior for both `copying` and `license` file names.
> Consider files named `copying` the same as `license` files

- business/noticeService.js
Many npm packages file paths start with "package/" if we only consider the root directory, the npm package license file will be skipped.
> Fix npm license file are not found

- providers/stores/mongoConfig.js
Before deploy, need to add the corrected environmental variable to dev-api and prod-api Azure app services.
> correct spelling error in environmental variable name

- business/definitionService.js
- providers/curation/github.js
- routes/definitions.js
Fixes #742
One this is merged, if someone makes POST to `definitions` with a malformed component, like this:
```bash
curl -X POST "https://clearlydefined.io/definitions" -H "accept: application/json" -H "Content-Type: application/json" -d "[\"npm/npmjs/redie/0.3.0\",\"npm/npmjs/-/redie/0.3.0\"]"
```
They will receive a more useful error:
```bash
curl -X POST "https://clearlydefined.io/definitions" -H "accept: application/json" -H "Content-Type: application/json" -d "[\"npm/npmjs/redie/0.3.0\",\"npm/npmjs/-/redie/0.3.0\"]"
An error occured when trying to fetch coordinates for one of the components: Coordinates npm/npmjs/redie/0.3.0 appear to be malformed. Are they missing a namespace or revision?
```
> Returns error when coordinates are malformed

- providers/summary/clearlydefined.js
- test/summary/clearlydefinedTests.js
This fixes #755 for new Maven components, but does not yet address how to correct all of the incorrect urls already in the databases. Opening as a draft until I figure out how to do that.
> corrects maven url

- routes/auth.js
We should only need to read user info, not write to it
Fix for #800 
This is a bit of an experiment - I cannot test it locally due to a GitHub OAuth app requiring a callback URL that is available over the open internet. Once this is merged and deployed to staging, I will test it there. If it breaks anything, I will role it back.
> limits scope of auth token 

- providers/summary/clearlydefined.js
- test/summary/clearlydefinedTests.js
This is similar to #794 - only it corrects the maven urls for source archives (which are also maven packages)
> updates the urls set for source archive packages

- lib/utils.js
- providers/harvest/process.js
- test/providers/harvest/processTest.js
After creating a curation PR in GitHub, service doesn't save curation data into mongo immediately.
Instead, it saves curation to mongo when GitHub webhook sent PR events. Because of this latency, the auto
curation code may create multiple PRs since harvest events trigger it.
To solve the issue, only run auto curation code for clearlydefined harvest tool event.
> Bug: duplicate auto curations have been created.

- lib/licenseMatcher.js
- test/lib/licenseMatcher.js
For Nuget component, the matching logic will produce a false positive. 
[Here](https://github.com/clearlydefined/curated-data/pull/10279) is an example. For Sustainsys.Saml2, any version before 2.0.0 should be `LGPL-3.0-or-later` and any version after 2.0.0 should be `MIT`. But the matching logic adds 1.x version as `MIT`. The reason is that both 2.x and 1.x have empty license files and license expression property. What’s more, the `licenseUrl` point to the same GitHub license page, but the license page content has changed. Let's first skip `licenseUrl` for Nuget component if the URL point to a GitHub file.
> Skip Nuget licenseUrl if it's from the GitHub

- providers/curation/github.js
- routes/webhook.js
- schemas/curations-1.0.json
- test/providers/curation/github.js
- test/providers/curation/githubPRs.js
- test/routes/webhookGitHubTests.js
Because 1/3 of the PRs created by engineers are incorrect. Adding versions with a wrong license in the PRs makes curators hard to change. Therefore, automatically create a new curation PR after an engineer-created PR has been reviewed, corrected, and merged.
> Automatically create curation PR for matching revision when PR get merged

- providers/curation/process.js
- test/providers/curation/processTest.js
When curation PR get merged, an auto curation PR should be triggered. The GitHub
event goes to a queue instead of directly sent to service.
> Bugfix: GitHub events are sent to a queue instead of directly to service

- providers/curation/github.js
1. Use uniqBy incorrectly
uniqBy(coordinatesList, ['type', 'provider', 'namespace', 'name']) could not
filter out coordinatesList based on type, provider, namespace, and name.
Use uniqWith instead.
2. If curation is not for license, skip auto curation
If curation.licensed.declared is undefined, when writing to a yml file, it will
throw the following error
```
YAMLException: unacceptable kind of an object to dump [object Undefined]
at writeNode (/opt/service/node_modules/js-yaml/lib/js-yaml/dumper.js:756:13)
at writeBlockMapping (/opt/service/node_modules/js-yaml/lib/js-yaml/dumper.js:634:10)
at writeNode (/opt/service/node_modules/js-yaml/lib/js-yaml/dumper.js:727:9)
at writeBlockMapping (/opt/service/node_modules/js-yaml/lib/js-yaml/dumper.js:634:10)
at writeNode …
```
> Fix reprocess api bugs

- lib/licenseMatcher.js
- providers/curation/github.js
- test/lib/licenseMatcher.js
- test/providers/curation/github.js
1. Fix this wrong PR description: clearlydefined/curated-data#10605
2. Log Nuget license URL for future analysis
3. Filter out Nuget deprecated license URL
4. Avoid auto curation for an undefined version of a component. https://github.com/clearlydefined/curated-data/pull/10530/files
> Some small fixes

- providers/curation/github.js
- routes/curations.js
1. Skip auto curation for components with existing scanned declared license
2. Add reprocess API protection. (100 is not a very accurate number. Use it for now.)
> Fix bugs for multi-version curation feature

- providers/curation/github.js
If existing declared license is NOASSERTION or empty, create auto curation.
> If existing declared license is NOASSERTION or empty, create auto curation

- providers/summary/fossology.js
- providers/summary/licensee.js
- providers/summary/scancode.js
- test/business/definitionServiceTest.js
- test/business/evidence/crate-quote-0.6.4.json
- test/business/evidence/crate-quote-1.0.9.json
- test/business/evidence/crate-rand-0.8.2.json
- test/business/evidence/crate-regex-1.5.3.json
- test/business/evidence/crate-serde-1.0.123.json
- test/business/evidence/crate-slog-2.7.0.json
- test/summary/clearlydefinedTests.js
Added some Rust multi-licensing tests to help diagnose https://github.com/clearlydefined/service/issues/856
* A couple of tests of the `clearlydefined` scanner, which show that it is correctly declaring the Rust licenses
* Another test that runs some real raw data through the multiple scanners and aggregrator.  This demonstrates that Rust multi-licenses are declared incorrectly, and is useful to run under a debugger with breakpoints to view/understand the operation.
The latter test should possibly be moved into a separate "functional" test, as it is testing real data through multiple components.  I plan to clean it up to run through multiple example data files to confirm that they are all declared as expected.
I'm not sure whether the raw data files should be in an `evidence` directory, …
> Fix for Rust multi-license declaration, plus new Rust license tests

- docs/architecture/go_components.md
Take 3 of the Go coordinate architecture - this time using URL encoding for slashes in import paths.
> Go architecture take 3

- business/definitionService.js
- business/noticeService.js
- providers/curation/github.js
- providers/stores/azblobAttachmentStore.js
- routes/definitions.js
- routes/notices.js
- test/business/definitionServiceTest.js
1. `/definitions` API sometimes is slow when no existing definition.
2. `/notice` API sometimes is slow.
> Add logs to analysis >100s calls

- providers/curation/github.js
- providers/curation/process.js
- routes/webhook.js
- test/providers/curation/processTest.js
- test/routes/webhookGitHubTests.js
When the `GET /definitions` request is as slow as 100s, there are many times that logs show around 1 minutes run time when getting the `curations-data` repo source code file tree. After dig into the `geit` npm package, I found that in order to get the file tree, there are one Github calls and 836 iterations when processing file blobs. What's more, the number of iterations will grow with the growth of curation-data repo. While the curation tree is not changed very often, cache it would help improve the perf of those slow API calls.
> Cache curation-data source code file tree to improve perf

- business/definitionService.js
- business/noticeService.js
We saw 3 time out errors this morning around the use of the notices API. While not widespread, it's still something we need to solve. This adds some additions to logging to enhance searching and parsing of our logs for calls to /notices.
> adds a few logging enhancements

- app.js
- lib/utils.js
- routes/definitions.js
- test/lib/util.js
This is a fix for #884 
When go support was deployed to staging and production, I discovered that when someone requests a definition with url encoded slashes, such as:
```
definitions/go/golang/github.com%2fgorilla/mux/v1.7.3
```
The load balancer decodes the slashes before the request is passed to the service, which means the coordinates requested are:
```
definitions/go/golang/github.com/gorilla/mux/v1.7.3
```
Which results in a 404 not found, as there are more parameters in the url than the route expect.
This fix is a bit brute force, but it does work. It allows for up to three additional parameters in the URL and, for go components only, strings the relevant arguments together, then parses the revision, name, and namespace out of that string.
> Fix go namespace slashes

- routes/harvest.js
- test/routes/harvest.js
summarizeService has one public function: summarizeAll .  Adapted raw data from harvest store with tool information and use summarizeService.summarizeAll instead.  Also added the related test.
Task: https://github.com/clearlydefined/service/issues/887
> Fixed "summarizeService.summarize is not a function"

- .eslintrc.json
- package.json
eslint@^7.5 supports optional chanining.  Update eslint to avoid optional chaining error.
> Upgrade eslint to ^7.5

- Dockerfile
- azure-pipelines.yml
When testing #893, I noticed that the [Optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) was not working in our builds. This is because our Docker image is based on Node 12, rather than Node 14.
Node 12 is technically still supported, but [will be EOL'd in April 30, 2022](https://nodejs.org/en/about/releases/). It's worth looking into upgrading to Node 14 (no, there is not a Node 13), rather than continuing to use Node 12.
I've done a local build of Node 14 and run tests (all passed) and done a quick click through of the API. It *seems* to work fine.
Anyone have ideas on how else we should test this? (And we should definitely not deploy this on a Friday).
> updates Dockerfile to use Node 14

- test/lib/util.js
This date/time parser library continues to be a pain, but thankfully @qtomlinson is exploring options to replace it in #789 
> comments out troublesome test case

- business/definitionService.js
- lib/utils.js
- test/lib/util.js
A community member brought these two definitions to my attention:
* https://clearlydefined.io/definitions/pypi/pypi/-/python-openstackclient/5.5.1
* https://clearlydefined.io/definitions/pypi/pypi/-/zuul/3.3.0
Because a source url is not found when these definitions are harvested, they have very low scores.
This is in part because pypi does not include source urls in its metadata (at least, not in a consistent way). 
This pull request adds a default source location for pypi definitions - the package's page on the central pypi registry (which allows for downloading of the source code and (in the project's README) often also has a link to the package's source code repo. We do something similar with go packages, since the go ecosystem also does not have a consistent way to identify source …
> Use pypi link for source

- routes/definitions.js
Over the past month we have seen a massive increase in calls to this batch definition API. Unfortunately, that has been causing some service availability issues. This pull request halves the limit of how many definitions can be requested at once. We will see if this increases the availability of our service. If anyone sees issues as a result of this, please reach out to me.
> lowers the limit of how many definitions can be requested at once

- routes/originMaven.js
Without user-agent in request headers, requests to maven central now fail.  Fixed this by adding user-agent to request headers for maven central.
Tasks: https://github.com/clearlydefined/website/issues/923
> Added user-agent to request headers for maven cental

- schemas/definitions-get-dto-1.0.json
Before the change when `expand` is not `-files`, the message is `should be equal to one of the allowed values`, which is not very useful.
After the change, the error message becomes `expand only support '-files'`.
> Make the error message more understandable

- providers/curation/github.js
This is to ensure when the merged pull requests are used to update
curation db sequentially, older data will be correctly overwritten
by newer data.
Tasks: https://github.com/clearlydefined/service/issues/901
> Retrieve closed pull requests from oldest to newest during syncAllContributions

- lib/utils.js
- test/lib/util.js
Even though Scancode and Licensee could find the license file, 74% of Go Component could not find the declared license. The issue is that the root directory for Scancode and the licensee for Go component are wrong. '%2F' should also be replaced with '/'.
> Go component could not find declared license

- lib/scancodeMap.js
All Go components start with "golang.org/x" and have this [PATENT](https://cs.opensource.google/go/x/tools/+/master:PATENTS) file, Scancode could detect it as `google-patent-license-golang` file. Instead of convert `google-patent-license-golang` to NOASSERTION, I propose to change it to OTHER since it's a patent file.
> Propose to change NOASSERTION to OTHER for Google PATENTS file

- routes/originCrate.js
When calling crate search api:
'https://crates.io/api/v1/crates?per_page=100&q=bitflags',
403 status code is returned with an error message of "We require that all
requests include a `User-Agent` header..."
Add the required user-agent in headers.
Task: https://github.com/clearlydefined/service/issues/938
> Add user-agent header to orignCrate

- providers/curation/github.js
1. When Go components with %2f in the namespace, the curation YAML file path of the component in the [Git repo](https://github.com/clearlydefined/curated-data) could not be found.
For example, this component `go/golang/github.com%2Fcoreos/etcd/v3.3.10+incompatible` will generate path `curations/go/golang/github.com%2Fcoreos/etcd/v3.3.10+incompatible`
However, the actual file path is `go/golang/github.com/coreos/etcd/v3.3.10+incompatible` when fetched by `geit` package. We should replace `%2f or %2F` with `/` in the path.
2. Fix a small bug. `_cleanCurationTree()` requires a number or string but `_cleanCurationTree(pr)` pr is an object.
> Fix curation issue for Go components with %2f in namespace

- providers/search/memory.js
- test/providers/search/memoryTest.js
The dev and production deployment uses AzureSearch, where search for
pattern "npmjs/red" will return results including npm/npmjs/-/redis/0.1.0.
In addition, the search is case insensitive.
In comparison, memory search (typically used during local development)
searches strictly for coordinates string containing "npmjs/red".
Change to match by parts and case insensitive.  This is to make
memory search more consistent with AzureSearch.
> Change memory search to match by parts and case insensitive

- routes/definitions.js
- Added verbose AI logging to the POST `/definitions` endpoint to help troubleshoot perf issues
> Added temporary verbose logs to investigate perf issues

- providers/search/memory.js
- routes/definitions.js
- test/providers/search/memoryTest.js
- Adding verbose telemetry for POST to /defintions
- Change memory search to match by parts and case insensitive
> Adding verbose telemetry for POST to /defintions

- package-lock.json
- package.json
- providers/stores/mongo.js
- test/fixtures/store/definitions-paged-no-files
- test/providers/store/mongoDefinition.js
- test/providers/store/mongoDefinitionPagination.js
The continuation token was generated based on _mongo.partitionKey. This is correct when _mongo.partitionKey is the only sort field.  When there are other sort fields in the query, the sequence of records are influenced by those fields. Continuation token based on only _mongo.partitionKey value does not produce the correct results for next pages.
There is a npm package on "cursor based pagination": https://www.npmjs.com/package/mongo-cursor-pagination The library supports one "paginatedField".  The ClearlyDefined api supports sort resulting in multiple sort fields. For example: sort on namespace sorts on three fields: ['coordinates.namespace', 'coordinates.name', 'coordinates.revision'].  So the library is not sufficient for CD's need.
To generate the correct next page, the continuation …
> Fixed incorrect continuation token when searching with sort

- providers/summary/scancode.js
- test/business/definitionServiceTest.js
- test/business/evidence/composer-packagist-mmucklo-krumo-0.7.0.json
For composer components, files are packaged under one single sub directory in the root directory. The license file contained in the sub directory is not picked up.  Solve by traversing into the subdirectory to detect license file.
Task: https://github.com/clearlydefined/service/issues/846#issuecomment-1411265574
> Fix NoAssertion for some composer components

- business/aggregator.js
- providers/summary/fossology.js
- providers/summary/licensee.js
- providers/summary/scancode.js
- test/business/definitionServiceTest.js
- test/business/evidence/crate-mpmc-0.1.6.json
For crate components, the license declared by clearlydefined summarizer is the preferred choice.  See Commit "Fix handling of Rust crates with license choices".
In the problematic case of
https://clearlydefined.io/definitions/crate/cratesio/-/mpmc/0.1.6, scancode detected that the license is BSD-2-Clause-Views.  The component's license retrieved from the package repository is "non-standard". This is converted to NoAssertion in the clearlydefined summary, and later set to be the package's license.
The solution is to move the logic of overriding crate license information to aggregator and only override when the license declared by clearlydefined summary is not "NOASSERTION".
Task: https://github.com/clearlydefined/service/issues/846#issuecomment-1405725749
> Fix NoAssertion for crate component

- DevDockerfile
- Dockerfile
- azure-pipelines.yml
Node.js v14 will go EOL on 30th April 2023[^1]. Node.js v18 is the latest LTS release of Node.js and will be supported until 30th April 2025
[^1]: https://github.com/nodejs/release#release-schedule
> Target Node.js v18

- package-lock.json
`lockfileVersion` 1 is used by npm v5 and v6. `lockfileVersion` 3 is used by npm v9 (the latest major version) but is backwards compatible:
> - `1`: The lockfile version used by npm v5 and v6.
> - `2`: The lockfile version used by npm v7 and v8. Backwards compatible to v1 lockfiles.
> - `3`: The lockfile version used by npm v9. Backwards compatible to npm v7.
See [the documentation][1] for more information
Fixes this warning in the build:
```
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
```
Generated with npm version `9.6.4`
[1]: …
> Regenerate lockfile from v1 to v3

- providers/stores/mongoConfig.js
To be consistent with other mongo definition store related variables
> Rename trimmed definition variable

- providers/curation/github.js
- test/providers/curation/github.js
The comment auto generated by service always point to the production web ui.  An example is at:
https://github.com/clearlydefined/curated-data-dev/pull/1275#issuecomment-1622265240.
Refactor the existing code into a function for reuse to auto generate comment correctly on dev server.
> Fix curation review url to point to the corresponding server

- package-lock.json
- package.json
- tsconfig.json
This adds a minimal TypeScript configuration necessary to type check the codebase. This is enough for an IDE that integrates with the TypeScript language service to run and show warnings and errors. You can also run this manually from the CLI with `tsc --noEmit`.
Related to #971
> Add minimal TypeScript configuration

- .npmrc
This ensures that dependencies are installed with an exact version, instead of a semantic version range specifier. See [the documentation][1] for more information.
[1]: https://docs.npmjs.com/cli/v8/commands/npm-install#save-exact
> Use `save-exact` in `.npmrc`

- providers/summary/scancode.js
- test/fixtures/scancode/0.0.0/npm-basic.json
- test/providers/summary/scancode.js
Instead of triggering the code path at https://github.com/clearlydefined/service/blob/4ae722e9eaad2bada374df687c0a5dad9e1efe18/providers/summary/scancode.js#L82-L83, this test previously just tested its own `throw new Error` line. This is now fixed and the expected error message and fixture adjusted to make the test actually work.
> Fix previously broken test

- .github/workflows/build_and_deploy_dev.yml
- app.js
- bin/config.js
- routes/index.js
* Partially addresses #1026 
This PR adds a GitHub action to perform the deploy of service to the dev service app in Azure.  To support debugging, it also adds the sha of the current deploy to the status endpoint.
_NOTE: As part of this work, Azure auth credentials were created following this [documentation](https://github.com/Azure/login#login-with-a-service-principal-secret)._
* create a bot user (e.g. clearlydefinedopts-bot and update credentials to use this bot
* permanently disable Azure DevOpts pipeline for dev service
* setup prod service to use a GH action to complete Issue #1026
* #1027
> add github action to build and deploy the dev CD/service

- providers/stores/mongoConfig.js
**NOTE: This is merging into prod branch to allow release of v1.1.0 as a minor release.**. It will be backported to master branch.
----
Deprecated config: TRIMMED_DEFINITION_MONGO_COLLECTION_NAME
Replacement config: DEFINITION_MONGO_TRIMMED_COLLECTION_NAME
Config TRIMMED_DEFINITION_MONGO_COLLECTION_NAME was removed in PR https://github.com/clearlydefined/service/pull/987. To avoid a major version change in the next release, the config is being added back in and deprecated.
New processing:
- if the old config has a value, a deprecation message is written to the console
- if the new config is specified, its value is used and the old one is ignored if it exists
- if only the old config is specified, its value is used
- otherwise, if neither are specified, the default is used
> deprecate config TRIMMED_DEFINITION_MONGO_COLLECTION_NAME

- package-lock.json
- package.json
* MERGE AFTER PR #1046
Normally, setting the version happens in master just before it is merged into prod in preparation of a release.  Since the code to be released is already in prod branch and master branch has newer commits, this needs to be added directly to prod.  Once merged into prod branch, it will be backported to master.
Used `npm version 1.1.0` to generate.  ([documentation](https://docs.npmjs.com/cli/v8/commands/npm-version)]
> prepare for release v1.1.0 by updating the version

- .github/workflows/build_and_deploy_prod.yml
_NOTE: This will merge into prod and then be back ported to master._
----
The GitHub action in this PR deploys prod branch to the production service webapps in US and Europe.  It uses the docker image built by the action and published to ghcr.
The action in this PR is very similar to the action for dev deploy in PR #1021.  Once this is merged in both prod and master, consider merging the two actions.
The main differences are:
* deploy on release
* deploy to US prod and EU prod
This is the same action that was being merged into master.  Because of the need to have this in prod for the release, this PR is replacing PR #1030.
> add GitHub action for deploy of production service

- .github/workflows/build_and_deploy_prod.yml
If the action is triggered by a release, `${{ github.event.release.tag_name }}` has the version.  If we manually run this action manually, `${{ github.event.release.tag_name }}` is empty.
To always have the version for tagging the created docker image and to pass to the webapp, this PR gets the version directly from the package.json file.
_NOTE: The package.json file must have the correct version when running manually._
> get version from package.json instead of release

- lib/pypiCoordinatesMapper.js
- test/lib/pypiCoordinatesMapper.js
In PyPI, '/' is invalid in a package name (see https://peps.python.org/pep-0508/#names).  Add a check to restrict the coordinates name prior to querying the PyPI API.
> Restrict PyPI coordinates name in PypiCoordinatesMapper

- lib/pypiCoordinatesMapper.js
- test/lib/pypiCoordinatesMapper.js
This is to fix the CodeQL scanning failure and make stubbing network call easier in unit tests.
> Use dependency injection in PypiCoordinatesMapper

- docs/rampup.md
- minimal.env.json
Updates the `minimal.env.json` file and the `rampup.md` files to mention the now-required `WEBHOOK_GITHUB_SECRET` and `WEBHOOK_CRAWLER_SECRET` secrets. This is a follow-up to changes in #1058
> Add now-required env vars to docs and minimal.env.json

- .github/dependabot.yml
This will hopefully reduce the number of Dependabot PRs by grouping some dependencies and thereby make continuous maintenance of dependency updates a little easier.
See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
> Add groups to Dependabot config

- routes/originConda.js
Service App fails to start with the following exception:
service-1  | Exception:
service-1  | TypeError: Cannot read properties of undefined (reading 'params')
service-1  |     at getOriginCondaRevisions (/opt/service/routes/originConda.js:40:43)
service-1  |     at Object.<anonymous> (/opt/service/routes/originConda.js:37:65)
service-1  |     at Module._compile (node:internal/modules/cjs/loader:1364:14)
service-1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
service-1  |     at Module.load (node:internal/modules/cjs/loader:1203:32)
service-1  |     at Module._load (node:internal/modules/cjs/loader:1019:12)
service-1  |     at Module.require (node:internal/modules/cjs/loader:1231:19)
service-1  |     at Module.patchedRequire [as require] …
> Fix originConda route

- .github/workflows/build-and-deploy-prod.yml
The reusuable workflow was expecting a boolean value for `is-release`.  It was passing `'true'` instead of `true`.
Instead of fixing that type mismatch here, the is-release check was moved to the reusable `app-build-and-deploy` workflow.  See [operations release v1.1.0](https://github.com/clearlydefined/operations/releases/tag/v1.1.0) for more information.
> fix failure of prod deploy due to invalid `is-release` value

- .github/workflows/build-and-deploy-dev.yml
Fixes #1155 
----
The v2.0.0 deploy workflows moved many of the complex scripts to files that can be tested.  This identified several bugs that when fixed allowed the service-dev to deploy successfully.  The change also adds a new job to upload the package-lock.json file to the build artifacts.  This is needed for the build-and-deploy job to be able to get the version from that file.
* https://github.com/clearlydefined/operations/pull/86
* https://github.com/clearlydefined/website/pull/1058
> update deploy scripts to v2.0.0 

- routes/originMaven.js
- test/fixtures/origins/maven/12345-1234.json
- test/fixtures/origins/maven/12345.json
- test/fixtures/origins/maven/org.apache.httpcom.json
- test/fixtures/origins/maven/org.apache.httpcomponents-response.json
- test/fixtures/origins/maven/org.apache.httpcomponents.json
- test/routes/origins.js
Below are the tasks completed as a part of this fix -
List of testcases added in the origins.js file related to the changes -
- Return suggestions when incomplete group id is provided as input
- Return list of artefacts when complete group id is provided as input
- Return blank response when group id is invalid and suggestions are not present
- Return blank response when group id and artefact id are invalid and suggestions are not present
This fix is related to [Issue 1167](https://github.com/clearlydefined/service/issues/1167)
> Fixed origins api for maven components throwing 500 error when invalid group id is provided

- .github/workflows/test.yml
When merging master into prod as part of the deploy process, the test workflow should be automatically started.  This also provides the option to run the test workflow manually.
This is consistent with the same workflow in the crawler.
> auto-start test workflow when PR into prod

- package-lock.json
- package.json
The latest version of clearlydefined/spdx that includes the LicenseRef support in parser and scanner are in v0.1.9.
> Update spdx to v0.1.9

- .github/workflows/build-and-deploy-dev.yml
- .github/workflows/build-and-deploy-prod.yml
- package-lock.json
- package.json
Updates the CD/service version to 2.0.1 in prep for a bug release that includes a bug fix in the deploy process.
operations v3.1.1 had a bug that prevented a successful deploy.  The operations v3.1.2 release fixed that bug.  Need to use this version and re-deploy.
> set version to v2.0.1 in prep for bug release including deploy with operations v3.1.2

- lib/curation.js
- test/lib/curation.js
When the curated license contains NOASSERTION (e.g., MIT AND NOASSERTION), the curation should be invalid.  In addition, when the curated license is not normalized, include the normalized license expression in the error message.
In the future, we can consider ignoring the cases of SPDX identifiers as per [SPDX specification](https://spdx.github.io/spdx-spec/v2-draft/SPDX-license-expressions/#d2-case-sensitivity).  For example, "MIT, Mit and mIt should all be treated as the same identifier".
> Fix curation validation

- app.js
- bin/config.js
- business/definitionService.js
- providers/index.js
- providers/queueing/memoryQueue.js
- providers/upgrade/azureQueueConfig.js
- providers/upgrade/defUpgradeQueue.js
- providers/upgrade/defUpgradeQueueConfig.js
- providers/upgrade/defVersionCheck.js
- providers/upgrade/memoryQueueConfig.js
- providers/upgrade/process.js
- test/business/definitionServiceTest.js
- test/providers/queueing/memoryQueueTest.js
- test/providers/upgrade/defUpgradeQueue.js
- test/providers/upgrade/defVersionCheck.js
- test/providers/upgrade/process.js
- test/providers/upgrade/processTest.js
**Performance Degradation During Schema Version Upgrade**
During the process of upgrading the definition schema version, performance degradation has been observed. Currently, schema version updates are handled by recomputing the definition on the fly, which causes slower performance. These updates are critical for data correctness and to introduce the LicenseRef marker.
**Proposed Solution:**
1. **Current Implementation (versionCheck):**
- Checks the schema version and recomputes the definition on demand if it is stale.
- This approach is currently in production.
2. **Preferred Approach (upgradeQueue):**
- When a request is received, return the existing definition.
- If the schema has changed, trigger a recompute after returning the result.
- Use a queue to handle the upgrade, similar to …
> Add the ability to queue definition recomputation

- providers/upgrade/azureQueueConfig.js
- providers/upgrade/defUpgradeQueue.js
- providers/upgrade/process.js
- test/providers/upgrade/defUpgradeQueue.js
- test/providers/upgrade/processTest.js
-Adjust logging
-Add context information to errors thrown during definition recomputation. 
-Add more tests
-Introduce DEFINITION_UPGRADE_DEQUEUE_BATCH_SIZE
> Adjust logging and allow configuration of batch size for dequeueMultiple

- .github/workflows/test.yml
Recently, ubuntu-latest is updated to ubuntu-24.04 (see https://github.com/actions/runner-images/blob/main/README.md).  This caused tests failures.  Pin runner version to ubuntu-22.04 as a resolution.
A successful test run can be found [here](https://github.com/qtomlinson/service/actions/runs/12757896561)
> Pin runner version

- lib/fetch.js
- lib/github.js
- lib/gitlab.js
- middleware/github.js
- routes/auth.js
- routes/originCrate.js
- routes/originMaven.js
- test/lib/fetchTests.js
This pull request is aimed at refactoring the `fetch.js` file to introduce a `defaultHeader` variable. This variable will be used as the default header across all Axios requests within the service repository, providing a more streamlined and maintainable approach to request configuration.
1. **Introduction of `defaultHeader`:**
2. **User-Agent Header Replacement:**
3. **Test Case Updates:**
This PR is related to [#1090](https://github.com/clearlydefined/service/pull/1163)
> Refactoring default header in fetch.js in Service

- lib/pypiCoordinatesMapper.js
- routes/originPyPi.js
Based on docs at https://packaging.python.org/en/latest/guides/migrating-to-pypi-org/, "the default interface for browsing packages is pypi.org. The domain pypi.python.org now redirects to pypi.org, and may be disabled sometime in the future."
Also see pypi json api documentation at https://docs.pypi.org/api/json/
Update the urls for the pypi json api in originPypi and pypiCoordinatesMapper to reflect this.
> Update pypi base url

- app.js
- business/definitionService.js
- package-lock.json
- package.json
- providers/harvest/cacheBasedCrawler.js
- providers/harvest/crawler.js
- providers/harvest/crawlerConfig.js
- providers/harvest/crawlerQueue.js
- providers/harvest/crawlerQueueConfig.js
- test/business/definitionServiceTest.js
- test/providers/harvest/cacheBasedCrawlerTest.js
Stats from 2025-03-16 to 2025-04-17 for the "get definition" process:
- Averaging 17 million "definition not available" counts daily (with 8.5 million definition computations triggering harvest requests).
- Averaging 250,000 distinct coordinates with "definition not available" daily.
1. **Duplicate Harvest Requests**:
- **Queue Growth**: The queue expands due to redundant harvest requests.
- **Scanner Tool Failures**: The crawler retries a failed request up to 5 times. The additional repeated queuing of the failed components forces the crawler to fail-retry more than necessary, thereby hindering overall progress.
2. **Duplicate Definition Computations**:
- Definition computations for unavailable definitions involve 4 network calls, adding load on internal dependencies (stores and queue). …
> Optimize Queueing and Definition Retrieval for Component Requested For Harvest

- business/definitionService.js
- providers/harvest/process.js
- routes/webhook.js
- test/business/definitionServiceTest.js
- test/providers/harvest/processTest.js
- test/routes/webhookCrawlerTests.js
Upon the availability of harvest tool results, the service currently recomputes the component's definition. As there are four harvest tools involved in the harvest process, this results in the definition being computed up to four times per component. 
Further analysis of harvest result timings from March 24 to April 24 indicated that approximately 80% of components have two or more results available within a 5-minute window.
Additionally, based on a 5-day analysis from April 19 to April 24, 50% of components have all four tool results available within the same 5-minute window.
This presents an opportunity to optimize the process by reducing the number of definition calculations, ideally to one per component in 50% of cases.
To address this, a delay mechanism is implemented to defer the …
> Avoid definition computation if results are in the existing definition

- business/definitionService.js
In the `definitionService`, all logging messages are written in lowercase. To maintain consistency with the existing codebase, update the newly added logging messages accordingly.
> Update logging message

- test/providers/curation/githubPRs.js
- test/providers/summary/fossology.js
- test/providers/summary/scancode/legacy-summarizer.js
- test/providers/summary/scancode/new-summarizer.js
```
error TS2345: Argument of type 'Buffer' is not assignable to parameter of type 'string'.
```
and [DEP0005][1]
> The Buffer() function and new Buffer() constructor are deprecated due to API usability issues that can lead to accidental security issues.
[1]: https://nodejs.org/api/deprecations.html#DEP0005
> Resolve Buffer issues

- providers/harvest/cacheBasedCrawler.d.ts
- providers/harvest/cacheBasedCrawler.js
- providers/logging/logger.d.ts
- providers/logging/logger.js
This change defines the types in `logger.d.ts` and `cacheBasedCrawler.d.ts`, and references them in JSDoc in `logger.js` and `cacheBasedCrawler.js`. It's indicative of the approach I'm suggesting for introducing TypeScipt types to the codebase.
> Add types to `logger` and `cacheBasedCrawler`

- DevDockerfile
- Dockerfile
The implicit reference, `node`, makes assumptions that only work on Docker itself, and not on some other container image tooling. The fully-qualified equivalent is `docker.io/library/node`.
> Use a fully-qualified reference to the base container image
