clearlydefined/service

.gitignore
app.js
lib/config.js
package-lock.json
package.json
routes/webhook.js

This secures the webhook. You need to set the env var `CURATION_GITHUB_WEBHOOK_SECRET` to the same value you set the `secret` in the webhook config in GH. 
In this PR I also update the status of the PR check to 'pending' prior to validation, similar to other GH integrations like Travis CI, etc. It displays as "Validation in progress".

Secure the webhook

---

.eslintrc.json
lib/utils.js
providers/curation/github.js
providers/harvest/azblob.js
providers/harvest/file.js
providers/summary/clearlydescribed.js
routes/curations.js
routes/harvest.js
routes/index.js
routes/packages.js
routes/webhook.js

I want to write some tests for the webhook but noticed `npm test` was failing due to `eslint` errors. This PR fixes those errors, which were mostly related to unused vars. Since we don't have any existing tests I can't tell if I broke anything, so please verify.

Fix eslint errors

---

business/component.js
routes/packages.js
routes/swagger.yaml

Add a handy endpoint for getting a set of component definitions.

add definitions endpoint

---

app.js
routes/originMaven.js

Add some endpoints for searching maven components

initial Maven support

---

README.md
app.js
business/badgeCalculator.js
package-lock.json
package.json
routes/badges.js
routes/swagger.yaml
test/business/badgeCalculator.js
test/routes/badges.js

This is a beginning. Perhaps later we can update the calculation logic to be a little more sophisticated.
Thanks to @jeffmcaffer @mynameistechno @cohenmax9

Add a /badges endpoint for displaying on your project site

---

README.md
app.js
business/definitionService.js
lib/config.js
providers/curation/github.js
providers/stores/abstractStore.js
routes/definitions.js
routes/swagger.yaml
schemas/harvest.json

consolidate package/component/summary name on "definition"
this PR should just be renames, no semantic changes or new function.

definition rename

---

README.md
business/aggregator.js
business/definitionService.js
business/summarizer.js
providers/stores/abstractStore.js
providers/stores/azblob.js
providers/stores/file.js
providers/summary/clearlydescribed.js
providers/summary/scancode.js
routes/swagger.yaml
schemas/harvest.json
test/fixtures/curation-invalid.1.yaml
test/fixtures/curation-invalid.2.yaml
test/lib/curation.js
test/providers/store/fileScan.js
test/summary/scancode.js
test/summary/summarizer.js

for now at least.
* results => output
* few left over changes.

finish off the renames

---

providers/stores/file.js
providers/summary/clearlydescribed.js
providers/summary/scancode.js
test/summary/scancode.js
test/summary/summarizer.js

* extract from scancode
* extract from npm

add release date to the summarized data

---

business/aggregator.js
business/definitionService.js
business/summarizer.js
providers/curation/github.js
routes/swagger.yaml
schemas/curation.json
test/fixtures/curation-invalid.1.yaml
test/fixtures/curation-invalid.2.yaml
test/fixtures/curation-invalid.3.yaml
test/fixtures/curation-invalid.yaml
test/fixtures/curation-valid.yaml
test/summary/scancode.js
test/summary/summarizer.js

update uses of 'package' to be 'coordinates'

---

business/badgeCalculator.js
providers/summary/clearlydescribed.js
providers/summary/scancode.js
schemas/definition.json
test/business/badgeCalculator.js
test/fixtures/curation-valid.yaml
test/summary/scancode.js

Add new harvesting for package / top level declared licenses and update schemas capture the latest.

update licensed schema for attribution and declared

---

routes/auth.js

users authenticating should get back from the service a list of permissions they have. this enables the UI to properly enable/disable or hide/show elements.

get permissions on authentications

---

bin/www
lib/mockInsights.js
package-lock.json
package.json

The APPINSIGHTS_INSTRUMENTATIONKEY variable is set in the dev and prod environments so this will take effect as soon as it's deployed.

Adding App Insights to track service metrics

---

providers/stores/azblob.js

Issue https://github.com/clearlydefined/service/issues/124

Resolve StorageError: The specified block list is invalid

---

app.js
providers/curation/github.js
test/providers/github.js

Address issue https://github.com/clearlydefined/service/issues/121

Correct webhook link

---

business/definitionService.js
providers/curation/github.js
routes/swagger.yaml

DO NOT MERGE
this is some WIP of enabling one contribution to update multiple components.

some initial support for multiple changes per PR

---

business/definitionService.js
lib/entityCoordinates.js
providers/summary/scancode.js
routes/curations.js
schemas/curation.json
schemas/definition.json

Refactored the creation of definitions so declared licenses not saved on a per file basis

Definition schema refactor

---

providers/curation/github.js

Need name and email to be committer

fileBody committer object fixed 

---

.vscode/launch.json
app.js
business/definitionService.js
lib/config.js
lib/curation.js
lib/entityCoordinates.js
middleware/github.js
package-lock.json
package.json
providers/caching/redis.js
providers/curation/github.js
providers/stores/file.js
providers/summary/scancode.js
routes/curations.js
routes/swagger.yaml
schemas/curation.json
schemas/definition.json
schemas/harvest.json
test/business/definitionServiceTest.js
test/providers/caching/redis.js
test/summary/scancode.js

We unfortunately amassed quite a few changes in master and these need to be pushed to prod. The PR is more for a record of those changes than an actual review.

push lots of changes to prod

---

lib/utils.js
providers/stores/file.js
providers/summary/cdsource.js
providers/summary/clearlydefined.js
providers/summary/scancode.js
routes/swagger.yaml
routes/webhook.js
schemas/curation.json
schemas/definition.json
test/fixtures/curation-valid.yaml

Address a few issues with curations and the PR checks
* The releaseDate format was ambiguous. In the UI we show YYYY.MM.DD but the schema required a full date-time. Clarify this to be YYYY-MM-DD everywhere. Note there is a matching change in the website
* add nuget as a valid type and provider to the schema and in a few places in the code
This addresses at least some of the issues with the PR checks failing on seemingly valid contributions.

add nuget and clarify releaseDate schema

---

lib/utils.js
providers/curation/github.js
providers/stores/file.js
providers/summary/cdsource.js
providers/summary/clearlydefined.js
providers/summary/scancode.js
routes/swagger.yaml
routes/webhook.js
schemas/curation.json
schemas/definition.json
test/fixtures/curation-valid.yaml

Added nuget as a valid type and provider. Made releaseDate "YYYY-MM-DD" as opposed to requiring full date-time.

Nuget and releaseDate fix

---

routes/curations.js

Successful curation returns object that contains pr number and url to pr.

Pr link repo

---

lib/curation.js
providers/curation/github.js
test/lib/curation.js
test/providers/github.js

Few tweaks to remove complexity in some Curation construction code paths.

Simplify curation object construction and validation

---

routes/swagger.yaml

update server url for swagger

---

providers/summary/clearlydefined.js
providers/summary/scancode.js
test/summary/clearlyDefined.js
test/summary/scancode.js

Add tests for the ClearlyDefined summarizer and fix a couple issues

add ClearlyDefined tests and fixes

---

lib/config.js
providers/summary/fossology.js
providers/summary/index.js

This commit to add FOSSology summarization, to decode and parse nomos
output.

Add FOSSology summarization

---

lib/utils.js
package-lock.json
package.json
providers/summary/clearlydefined.js
test/lib/util.js

- hook up to the NuGet ClearlyDefined summarizer

add extractLicenseFromLicenseUrl util

---

app.js
business/definitionService.js
lib/entityCoordinates.js
lib/resultCoordinates.js
providers/stores/abstractStore.js
providers/stores/azblob.js
providers/stores/file.js
providers/summary/clearlydefined.js
routes/definitions.js
schemas/curation.json
schemas/definition.json

several sets of changes
* Handle maven source location having a real URL (or the older `group/artifact` format
* improve the file listing support
* make `reload` more robust

fix up maven source and file store support

---

business/aggregator.js
business/definitionService.js
business/summarizer.js
lib/utils.js
providers/summary/clearlydefined.js
test/business/definitionServiceTest.js
test/summary/clearlyDefined.js
test/summary/summarizer.js

Add some more tests and handle a few more cases of old style source locations and curations with source locations.

more source location robustness

---

business/definitionService.js
lib/attachmentCoordinates.js
lib/entityCoordinates.js
providers/curation/github.js
providers/stores/azblob.js
providers/stores/file.js
routes/attachments.js
routes/swagger.yaml
test/lib/attachmentCoordinates.js
test/providers/store/azblob.js

- fix attachments
- improve performance of definitionService

Release to production

---

providers/curation/github.js
routes/auth.js

Fixes #233
This needs to be merged at the same time of PR [#305](https://github.com/clearlydefined/website/pull/305)

Issue #233 (CI) - Enhance Contribution description (#1)

---

package.json

wasn't finding all the tests on `npm test` without this

add quotes around test path

---

providers/summary/clearlydefined.js
test/summary/clearlyDefined.js

This gives us a file browser for NuGet's

add NuGet manifest packageEntries to file list

---

lib/utils.js
providers/summary/clearlydefined.js
test/lib/util.js
test/providers/summary/clearlydefined.js

based on https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg-(Technical-Spec)#license-expression-pack

use licenseExpression from nuget manifest to declare license

---

providers/summary/scancode.js

use LICENSE file for git repo
use package.json/gemspec/etc for components

change order of licensed.declared for source vs package

---

bin/config.js

- let clearlydefined be number 1

change summarizer precedence

---

lib/utils.js

there are other improvements in flight for this, this is just a stopgap for now to help unblock a user

add license-mit and license-apache to _licenseFileNames

---

providers/summary/clearlydefined.js
routes/originPod.js

Implementation of all the required methods for CocoaPods integration.

CocoaPods integration

---

business/noticeService.js
routes/notices.js
schemas/notice-request.json
schemas/swagger.yaml
test/business/noticeServiceTest.js

This PR updates some of the names in the /notices API schema

update notices API

---

business/noticeService.js
schemas/swagger.yaml
test/business/noticeServiceTest.js

It looked like a bug to me when I looked at it, maybe others will too?
@jeffmcaffer what do you think?

remove missing property from noticeService

---

business/definitionService.js
providers/stores/abstractAzblobStore.js
providers/stores/abstractFileStore.js
providers/stores/mongo.js
routes/definitions.js
schemas/definitions-find.json
schemas/swagger.yaml
schemas/validator.js
test/lib/util.js
test/providers/store/mongoDefinition.js

POST to `/definitions/find`
see schema https://github.com/dabutvin/service/blob/5fee86e15f21e7ae80911567fd3b114511968f2e/schemas/definitions-find.json

Add find endpoint to defintions

---

providers/stores/mongo.js
routes/curations.js
test/providers/store/mongoDefinition.js

- also remove the try/catch/400 and let the app errorhandler take this

update mongo list() to find multiple revisions (fixes #375)

---

app.js
business/definitionService.js
business/statsService.js
providers/search/abstractSearch.js
providers/search/azureSearch.js
providers/search/memory.js
providers/stores/abstractAzblobStore.js
providers/stores/abstractFileStore.js
providers/stores/mongo.js
routes/stats.js

list the available stats: `/stats`
get each individual stat
`/stats/totalcount`
`/stats/npm`
`/stats/nuget`

Initial StatsService implementation

---

app.js
middleware/querystring.js
routes/definitions.js
schemas/definitions-find.json
test/middleware/querystringTest.js

we want to cache this with cloudflare so moving from POST to GET

move definition query into GET route

---

business/aggregator.js

- for a component with 0 files you can get a null ref

check length of array when normalizing files

---

business/definitionService.js
lib/utils.js
providers/summary/clearlydefined.js
schemas/definition-1.0.json

Add new described/urls section to the definition

---

providers/curation/mongoCurationStore.js
routes/curations.js

schema update to remove '.' from object keys to enable the query

update curation route to accept expand=prs

---

business/definitionService.js

to pick up the latest urls section

bump the definition schema version

---

app.js
providers/curation/github.js
providers/curation/githubConfig.js
providers/curation/mongoCurationStore.js
routes/curations.js
schemas/swagger.yaml
test/providers/curation/githubPRs.js

this will enable us to get them in batches for things like the browse page and loading a package-lock on the definition list

add POST for bulk curations

---

providers/curation/memoryStore.js

this was added to the github curation store, but not the memory one

add listAll method to curation memoryStore

---

business/definitionService.js
providers/summary/fossology.js
test/providers/summary/fossology.js
test/summary/fossology.js

- the copyrights have been severely over-reporting
- see https://github.com/fossology/fossology/issues/1292

disable fossology/copyright from summarizer

---

providers/curation/mongoCurationStore.js
test/providers/curation/mongoCurationStore.js

add test coverage to mongo curation store

fix null ref for curation with no data

---

app.js

dev 404:
prod 404:
dev error from a service:
prod error from a service:

swallow the error unless we are in dev

---

providers/curation/mongoCurationStore.js
test/providers/curation/mongoCurationStore.js

some webhooks are hitting this case

filter curations for full data sets during updates

---

business/definitionService.js

add lock by coordinates in computeAndStore

---

business/definitionService.js
lib/utils.js
providers/summary/clearlydefined.js
test/summary/clearlyDefined.js
test/summary/clearlydefinedTests.js

Issue #419 - Move URL computation to ClearlyDefined summarizer

---

business/definitionService.js

this gives us score on the top level, and the improved license merging

bump schema version for defintions

---

providers/summary/clearlydefined.js

Added support for Pypi download package extension

---

package-lock.json
package.json
providers/curation/github.js
test/providers/curation/githubPRs.js

we were checking github directly with HEAD requests
this was happening on the order of ~50K per day
our new curation requests started getting throttled

use smartgit to get curations out of github

---

business/definitionService.js

for propagating the changes to definition store dispatcher

bump schema version

---

package-lock.json
test/lib/spdx.js

bump satisifes to handle NOASSERTION, LGPL-2.1+

---

providers/summary/clearlydefined.js

Fix NPM packages download url structure

---

providers/harvest/crawler.js

getting inputs like maven/mavencentral/com.sun.faces/jsf-impl//2.1.0-b03
we can correct these here without causing too much fuss

ensure duplicate slashes are collapsed

---

lib/spdx.js
lib/utils.js
test/lib/util.js

proposed was always winning over declared

fix mergeLicensed method

---

schemas/definition-1.0.json

`ClearlyDefinfed` -> `ClearlyDefined`

Fix minor typo

---

providers/curation/github.js

example: https://github.com/clearlydefined/curated-data-dev/pull/881

commit curation as the logged in user (fixes #252)

---

lib/utils.js
test/lib/util.js
test/summary/clearlydefinedTests.js

update extractDate to filter out bogus dates

---

providers/stores/azblobHarvestStore.js
test/evidence/issue-312-2.0.11.json

investigations and tests around #312

---

business/definitionService.js
schemas/swagger.yaml

added "expand" to documentation

---

providers/stores/mongo.js
test/providers/store/mongoDefinition.js

multiple sort options

---

lib/curation.js
lib/utils.js
test/providers/curation/github.js

adding curation override on merge, fixes #526

---

business/suggestionService.js
providers/stores/mongo.js
test/business/suggestionServiceTest.js

if this property is not defined then the mongoDb omits from results
We were seeing missing data because of this

[suggestions] sort by release date on the client

---

lib/utils.js
test/providers/curation/github.js

fixes #537 and includes a test

adding override for license merge at package level

---

lib/utils.js
test/lib/util.js

top tldr licenses support

---

providers/curation/github.js

Resolves https://github.com/clearlydefined/service/issues/551

Non standard characters

---

schemas/swagger.yaml

This resolves #541 ; it's interesting since it's related to local harvesting (important for debugging purposes).

updated doc

---

routes/curations.js

Resolves #584 by adding an array of patch sources on the returned error information object.

adds patchesInError array with source of issues

---

routes/originGitHub.js

As mentioned in #599  , the API was returning just the 30 items, which hides some useful data.
Fixes #599

Increase origin search size

---

README.md
app.js
business/statsService.js
providers/summary/clearlydefined.js
routes/originComposer.js
schemas/curation-1.0.json
schemas/curations-1.0.json
schemas/definition-1.0.json
test/summary/clearlyDefined.js
test/summary/clearlydefinedTests.js

This PR is to address issue https://github.com/clearlydefined/crawler/issues/230 by starting to enable php license crawling.
Using https://github.com/clearlydefined/service/pull/273 as a guide

[PHP] Add packagist.org support (WIP)

---

providers/summary/clearlydefined.js
routes/originComposer.js
test/summary/clearlyDefined.js
test/summary/clearlydefinedTests.js

PHP composer corrections

---

app.js
providers/curation/github.js
routes/curations.js
test/providers/curation/github.js

Resolves #609 at @geneh suggestion

logging invalid curations on hook and from UI

---

schemas/swagger.yaml

Fixing Swagger by moving response to schema, now valid

---

schemas/definitions-find.json

expanded the definitions-find associated schema

---

.vscode/launch.json
package.json
test/app.js
test/providers/curation/github.js

Redone test, simplified.
This closes #595

Added Unit Test for application startup

---

lib/utils.js
test/lib/util.js

Related to https://github.com/clearlydefined/service/issues/636

Add license URL to _licenseUrlOverrides

---

providers/search/azureSearch.js

Resolves https://github.com/clearlydefined/service/issues/639

Resolve Azure Search errors

---

business/statusService.js

As requested, this resolves #598

adding tools ran per day status

---

lib/utils.js
providers/summary/clearlydefined.js
test/lib/util.js

Resolves https://github.com/clearlydefined/service/issues/652

Improve EULA license detection as Other based on licenseUrl

---

schemas/swagger.yaml

fixes #663 ; good catch from @sschuberth !

patches to array on swagger

---

test/providers/curation/github.js

modified test to match definition

---

routes/harvest.js

Resolves https://github.com/clearlydefined/service/issues/671

Increase bodyParser limit for harvest

---

lib/utils.js
test/lib/util.js

Resolves https://github.com/clearlydefined/service/issues/692

Improve NuGet license detection

---

middleware/github.js
middleware/permissions.js
routes/curations.js

Only use github data as needed

---

middleware/github.js
middleware/permissions.js
routes/curations.js

* Only use github data as needed

Merge to PROD: Only use github data as needed (#714)

---

docs/rampup.md

First draft, will link from other places soon.

Rampup doc for new maintainers

---

business/definitionService.js

Dont cache chonks and add a TTL for definitions

---

package-lock.json
package.json
patches/tiny-attribution-generator+0.1.2.patch

Upstream PR: https://github.com/amzn/tiny-attribution-generator/pull/28
Remove this patch when this is merged and released.

Patch tiny-attribution-generator with upstream PR for JSON output.

---

lib/utils.js
test/lib/util.js

Removing links that no longer point to EULA

---

docs/rampup.md

Small updates I discovered while getting my dev environment set up.

Update service docs

---

package-lock.json
package.json

This is meant to fix the vulnerability flagged in #730, as well as get us up to the latest version.

updates mocha to 8.2.1

---

docs/rampup.md

adds documentation of snyk and dependabot for dependency management

---

package-lock.json
package.json

(This is an updated version of #713)

updates eslint to more secure version

---

package-lock.json
package.json

updates nyc to a more secure version

---

test/lib/util.js

fixes failing util test in master

---

routes/definitions.js
test/routes/definitions.js

through an API call
This partially sets us up to fix #799  

Adds ability to force a recompute of a definition

---

lib/curation.js
test/fixtures/curation-invalid.10.yaml
test/fixtures/curation-invalid.11.yaml
test/fixtures/curation-valid.1.yaml
test/lib/curation.js

Added SPDX compliance validation and tests

---

.vscode/launch.json
app.js
bin/config.js
business/definitionService.js
lib/licenseMatcher.js
providers/curation/github.js
providers/curation/githubConfig.js
providers/harvest/process.js
providers/stores/abstractFileStore.js
routes/webhook.js
schemas/curations-1.0.json
test/business/definitionServiceTest.js
test/lib/licenseMatcher.js
test/providers/curation/github.js
test/providers/harvest/processTest.js
test/routes/webhookCrawlerTests.js

This is the implementation of the feature proposal discussed in #809 . The design document has changes made during development and some screenshots of example curations as well.
All the code is behind a feature flag. We'd like to merge, turn it on in dev, then experiment to make sure everything is working as expected.
This is developed by myself and @MichaelTsengLZ . We're available for discussion about any questions or concerns.

Implement Multiversion Curation feature

---

package-lock.json
package.json

Upgrade SPDX package version to fix SPDX validation of "OTHER" licenses

Upgrade SPDX package

---

.vscode/launch.json
providers/curation/github.js
routes/curations.js
test/providers/curation/github.js

This API is described in this [spec](https://docs.google.com/document/d/1MNzQ0h_qZVFNuEow7iHzi2APOmFuCzMSbEwcV5NGWjM/edit). The API will help us automatically open new curations based on historical curations.

Implement curations/reprocess API

---

routes/webhook.js
test/routes/webhookGitHubTests.js

validates contributions when a pull request is reopened

---

README.md
app.js
lib/utils.js
providers/summary/clearlydefined.js
routes/originMavenGoogle.js
schemas/curation-1.0.json
schemas/curations-1.0.json
schemas/definition-1.0.json
schemas/swagger.yaml
test/summary/clearlydefinedTests.js

Work in progress. Initial changes

Maven google support

---

package-lock.json
package.json

updates spdx package

---

package-lock.json
package.json

updates spdx version

---

providers/summary/clearlydefined.js

adds ability to handle multiple namespaces for gitlab components

---

docs/determining-declared-license.md

[Rendered](https://github.com/clearlydefined/service/blob/add-docs-for-declared-licenses/docs/determining-declared-license.md)

adds doc detailing how declared licenses are determined

---

routes/harvest.js

@nellshamrell As per our discussion, summarizeService.summarizeAll only takes two arguments, so the result of getFilter() is not currently used.  Removed getFilter related code.

Removed redundant code

---

business/definitionService.js

Need to pass in the coordinates.

Fix NPE retrieving definition with force set to true

---

DevDockerfile

use Node 14 in Dev Dockerfile as well

---

providers/curation/github.js

reduces cache times for curations from 24 hours to 4 hours

---

providers/summary/scancode.js

make 2.9.1 a valid ScanCode version

---

lib/utils.js
test/lib/util.js

Service side of fix for release dates for pods.
Task: https://github.com/clearlydefined/crawler/issues/450

Added parsing date with SQL format

---

providers/summary/clearlydefined.js

Task: https://github.com/clearlydefined/website/issues/963

Fix described.urls.version for pod

---

routes/definitions-1.0.0.js

The force query parameter has been transformed to boolean.

The force query parameter has been transformed to boolean

---

azure-pipelines.yml

Fix build error message:
##[error]The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04 or ubuntu-22.04 (ubuntu-latest). For more details, see https://github.com/actions/runner-images/issues/6002

Fix azure pipeline error

---

package-lock.json
package.json

Also removed package dependencies that are no longer used.

Update SPDX related versions

---

docs/rampup.md

trivial documentation change -- being used to test webhooks

use consistent periods

---

.github/workflows/update-scancode-licensedb.yml
scripts/transform-scancode-licensedb.js

A few small updates with fixes of problems I noticed after merging #1024

Update Actions workflow to pull in LicenseDB data

---

lib/pypiCoordinatesMapper.js

This is a test to check if this satisfies a GitHub code scanning warning.

Use URL object to generate request URL

---

.github/workflows/build-and-deploy-dev.yml

Reverts clearlydefined/service#1048
We're trying to determine if this is caused the current deployment issues in dev

Revert "remove docker secrets from deploy action"

---

.github/workflows/build-and-deploy-dev.yml

Reverts clearlydefined/service#1073
Turns out, this wasn't the cause after all 🙏🏼

Revert "Revert "remove docker secrets from deploy action""

---

package-lock.json
package.json
test/business/aggregatorTest.js
test/lib/spdx.js

- Update tests for v0.1.8, to reflect https://github.com/clearlydefined/spdx/pull/30
- Also added more tests
- This is a interim step before moving to use GitHub packages.

Update to @clearlydefined/spdx v0.1.8

---

.github/workflows/build-and-deploy-dev.yml
.github/workflows/build-and-deploy-prod.yml

Updates deployment pipeline.
Important that prod is updated as we will now send App Version and Build Sha to docker image when built.
This will be returned on GET `https://api.clearlydefined.io/`

Update deployment pipelines 3 1 1

---

.github/workflows/build-and-deploy-dev.yml
.github/workflows/build-and-deploy-prod.yml

Update deploy to 3.1.1 properly this time

---

package-lock.json
package.json

- `@types/chai`
- `@types/deep-equal-in-any-order`
- `@types/sinon`

Add more `@types` dependencies

---

package.json
providers/harvest/cacheBasedCrawler.js
providers/logging/logger.js
tsconfig.json

Enhancements:
- Integrated tsc as part of the linting procedure to improve consistency and reliability.
- Limited the scope of type checking to specific files.

Include TypeScript compiler in linting process
